version: "3.8"

services:
    app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        working_dir: /app
        command: bash
        stdin_open: true
        tty: true