version: "3.8"

services:
    app:
        build: .
        container_name: fastapi_app
        expose:
            - "8000"
        volumes:
            - .:/app
        working_dir: /app
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
        stdin_open: true
        tty: true
    nginx:
        image: nginx:latest
        container_name: nginx_proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/certbot/www:/var/www/certbot
            - ./nginx/certbot/conf:/etc/letsencrypt
        depends_on:
            - app