name: Ruff Lint Check

on:
  pull_request:
    branches: [main]
jobs:
  ruff-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          pip install ruff
      - name: Run ruff
        run: |
          ruff check .